---
title: "R Notebook"
output: html_notebook
---

```{r, message=FALSE}
library(tidyverse)
```

```{r, message=FALSE}
abund <- read.table("../../data/E-WADES/depths_M3.tsv", header=T,
                    row.names=1, sep="\t", check.names=F)
meta_sample <- read.table("../../data/E-WADES/meta_sample.tsv", header=T,
                    row.names=1, sep="\t", check.names=F) %>%
  select(City, Replicate_Bigger, Date) %>%
  mutate(City = str_replace_all(City, "Copenaghen", "Copenhagen")) %>%
  rownames_to_column("sample") 
taxon <-  read.table("../../data/E-WADES/taxonomy.tsv", header=T,
                    row.names=1, sep="\t", check.names=F)
```

```{r}
all(rownames(abund)==meta_sample$sample) &
all(colnames(abund)==rownames(taxon))
```

### Remove replicates from abundance matrix

```{r}
abund <- abund[meta_sample$Replicate_Bigger,]
meta_sample <- meta_sample[meta_sample$Replicate_Bigger,]
```


## Aggregate to Genus Rank

```{r}
genus_abund <- abund %>% rownames_to_column("sample") %>%
  pivot_longer(-sample, names_to="Species", values_to="count") %>%
  left_join(taxon%>%rownames_to_column("SpeciesID") %>% select(SpeciesID,Genus) %>%
              rename(Species=SpeciesID), by="Species") %>%
  reframe(count=sum(count), .by=c("sample","Genus")) %>%
  pivot_wider(names_from=Genus, values_from=count) %>%
  column_to_rownames("sample")

genus_rel_abund <- data.frame(genus_abund/rowSums(genus_abund))
```

```{r}
subset_genus <- colSums(genus_abund) %>% sort %>% tail(10) %>% names
```

```{r}
color_genus <- rownames(qualpalr::qualpal(n = length(subset_genus), 
                                          colorspace = list(h = c(0,360),
                                                            s = c(.25,.6),
                                                            l = c(.45,.85)))$RGB) %>%
  stats::setNames(subset_genus)
color_genus <- c(color_genus, "Other"="#A6A6A6")
color_genus
```

```{r}
data_composition <- genus_rel_abund %>%
  rownames_to_column("sample") %>%
  pivot_longer(-sample, names_to="genus", values_to="relative") %>%
  mutate(genus = if_else(genus %in% subset_genus, genus, "Other")) %>%
  left_join(meta_sample, by="sample") %>%
  filter(Replicate_Bigger) %>%
  reframe(relative=sum(relative), .by=c("sample","genus","City")) %>%
  group_by(sample) %>%
  mutate(Pseudomonas_E_rel = sum(relative[genus == "Pseudomonas_E"])) %>%
  ungroup() %>%
  arrange(Pseudomonas_E_rel) %>%
  mutate(sample_fct = factor(sample, levels = unique(sample)))

p.composition <- data_composition %>%
  ggplot(aes(x=sample_fct,y=relative,fill=genus)) +
    geom_bar(stat="identity", color=rgb(0,0,0,.25), linewidth=.25) +
    scale_fill_manual(values=color_genus,
                      labels = function(x) paste0("<i>", x, "</i>")) +
    theme_minimal() +
    theme(legend.position="bottom",
          axis.text.x=element_blank(),
          axis.ticks.x=element_blank(),
          legend.text = ggtext::element_markdown()) +
  ylab("Genus\nComposition") +
  labs(fill="Genus") +
  xlab("Samples") +
  ggnewscale::new_scale_fill() +
  geom_tile(data = data_composition,
            aes(x = sample, y = -0.03, fill = City), 
            height = 0.03, width = 1, inherit.aes = FALSE) 
p.composition
```

## Dimensionality Reduction

```{r}
# Calculate the distance matrix with bray-curtis and aitchison
dist.bray <- vegan::vegdist(abund, "bray") %>% as.dist
dist.aitc <- abund %>% 
  zCompositions::cmultRepl() %>%
  vegan::vegdist(method = "aitchison") 
```

## PCOA

```{r}
pcoa.bray <- stats::cmdscale(dist.bray, eig=T, add=T)
pcoa.aitc <- stats::cmdscale(dist.aitc, eig=T, add=T)
```

## Plot with Aitchison Distance

```{r, warning=FALSE}
centroids.pcoa.aitc <- pcoa.aitc$points %>% as_tibble %>%
  cbind("City"=meta_sample$City) %>%
  reframe(V1=mean(V1), 
          V2=mean(V2),
          .by=City)

varExplained_aitc <- 100 * (pcoa.aitc$eig / sum(pcoa.aitc$eig)) %>%
  round(2)

p.pcoa.aitc <-  pcoa.aitc$points %>% as_tibble %>% 
  cbind("City"=meta_sample$City) %>%
  ggplot(aes(x=V1,y=V2, color=City)) +
  geom_point(size=3) +
  stat_ellipse() +
  geom_point(data=centroids.pcoa.aitc, shape=21, size=5, color="black",
             aes(fill=City)) +
  theme_minimal() +
  xlab(paste("PCoA1 (~",varExplained_aitc[1],"%)", sep="")) +
  ylab(paste("PCoA2 (~",varExplained_aitc[2],"%)", sep="")) +
  theme(legend.position="bottom") +
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=12))

p.pcoa.aitc
```

```{r}
varExplained_bray <- 100 * (pcoa.bray$eig / sum(pcoa.bray$eig)) %>%
  round(2)

p.pcoa.bray <- pcoa.bray$points %>% as_tibble %>% 
  as_tibble() %>% mutate(Pseudomonas_E=genus_rel_abund[, "Pseudomonas_E"]) %>%
  ggplot(aes(x=V1, y=V2, fill=Pseudomonas_E)) +
    geom_point(size=4, shape = 21, color = "black") +
    theme_minimal() +
    xlab(paste("PCoA1 (~",varExplained_bray[1],"%)", sep="")) +
    ylab(paste("PCoA2 (~",varExplained_bray[2],"%)", sep="")) +
    #scale_color_viridis_c(option = "C") +
     scale_fill_gradient(
      low = "#2C3E50",  
      high = color_genus["Pseudomonas_E"]  # Same color associated to Pseudomonas_E genus
    ) +
    theme(axis.text=element_text(size=10),
          axis.title=element_text(size=12)) +
    theme(legend.position="bottom") +
    labs(fill = expression("Relative Composition of "*italic("Pseudomonas_E")))
p.pcoa.bray
```


## Merge the figures

```{r, fig.width=13.3, fig.height=10}
p1 <- p.composition + guides(fill=guide_legend(ncol=6))

p2 <- ggpubr::ggarrange(p.pcoa.bray + theme(legend.margin = margin(t = 20, b = 10)),
                        p.pcoa.aitc, ncol=2, labels=c("B","C"))

pall <- ggpubr::ggarrange(p1, p2, 
                          ncol=1, labels=c("A",""),
                          heights=c(0.4,0.6))
pall
```


```{r}
png(filename="E-WADES_pcoa_metrics.png", width=8000, height=6000, res=600)
pall
dev.off()
```

## Adonis 2

```{r}
meta_sample <- genus_rel_abund %>% as_tibble(rownames = "sample") %>%
  select(sample, Pseudomonas_E) %>%
  right_join(meta_sample, by = "sample") %>%
  mutate(City = case_when(
    str_detect(City, "Copenaghen") ~ "Copenaghen",
    TRUE ~ City
  ))
```

```{r}
vegan::adonis2(dist.aitc ~ City + Pseudomonas_E, data = meta_sample, 
               permutations = 10^3, by = "margin")
```

```{r}
vegan::adonis2(dist.bray ~ City + Pseudomonas_E, data = meta_sample, 
               permutations = 10^3, by = "margin")
```


## UMAP

```{r,message=FALSE, warning=FALSE}
library(uwot)
set.seed(42)
umap.bray <- uwot::umap(as.dist(dist.bray), min_dist = .5)

set.seed(42)
umap.aitc <- uwot::umap(as.dist(dist.aitc), min_dist = .5)
```

```{r}
p.umap.aitc <- umap.aitc %>% as_tibble %>% 
  cbind("City"=meta_sample$City) %>%
  ggplot(aes(x=V1,y=V2, fill=City)) +
  geom_point(size=4, shape = 21, alpha = .75) +
  theme_minimal() +
  xlab("UMAP-1") + ylab("UMAP-2") +
  theme(legend.position="bottom") +
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=12))

p.umap.aitc
```

```{r}
p.umap.bray <- umap.bray %>% as_tibble %>% 
    mutate(Pseudomonas_E=genus_rel_abund[, "Pseudomonas_E"]) %>%
    ggplot(aes(x=V1, y=V2, fill=Pseudomonas_E)) +
    geom_point(size=4, shape = 21, color = "black") +
    theme_minimal() +
    xlab("UMAP-1") + ylab("UMAP-2") +
    #scale_color_viridis_c(option = "C") +
     scale_fill_gradient(
      low = "#2C3E50",  
      high = color_genus["Pseudomonas_E"]  # Same color associated to Pseudomonas_E genus
    ) +
    theme(axis.text=element_text(size=10),
          axis.title=element_text(size=12)) +
    theme(legend.position="bottom") +
    labs(fill = expression("Relative Composition of "*italic("Pseudomonas_E")))
```

```{r, fig.width=10, fig.height=5}
p.umap <- ggpubr::ggarrange(
  p.umap.bray + theme(plot.margin = margin(b = 15, t = 5)) + ggtitle("E-WADES Bray-Curtis"), 
  p.umap.aitc + ggtitle("E-WADES Aitchison"), 
  ncol = 2
)
p.umap
```

```{r}
png(filename = "../Supplementary/EWADES_umap_metrics.png", width = 3000, height = 1800, res = 300)
p.umap
dev.off()
```

## Review

```{r}
pcoa.euc <- dist(abund) %>%
  stats::cmdscale(eig=T, add=T)
pcoa.JSD <- philentropy::distance(abund, method = "jensen-shannon") %>%
  stats::cmdscale(eig=T, add=T)
pcoa.CAN <- vegan::vegdist(abund, method = "canberra") %>%
  stats::cmdscale(eig=T, add=T)
pcoa.HEL <- vegan::vegdist(abund, method = "hellinger") %>%
  stats::cmdscale(eig=T, add=T)
```

```{r}
plot.PCOA.pseo <- function(pcoa, meta_sample, genus_abun){
  
  varExplained <- 100 * (pcoa$eig / sum(pcoa$eig)) %>%
    round(2)

  p <- pcoa$points %>% as_tibble %>% 
    as_tibble() %>% mutate(Pseudomonas_E=genus_abun[, "Pseudomonas_E"]) %>%
    ggplot(aes(x=V1, y=V2, color=Pseudomonas_E)) +
    geom_point(size=2) +
    theme_minimal() +
    xlab(paste("PCoA1 (~",varExplained[1],"%)", sep="")) +
    ylab(paste("PCoA2 (~",varExplained[2],"%)", sep="")) +
    scale_fill_gradient(
        low = "#2C3E50",  
        high = color_genus["Pseudomonas_E"]  # Same color associated to Pseudomonas_E genus
      ) +
    theme(legend.position="none") +
    theme(title = element_text(size = 16))

  return(p)
}
```

```{r}
plot.PCOA.city <- function(pcoa, meta_sample){
  
  varExplained_aitc <- 100 * (pcoa$eig / sum(pcoa$eig)) %>%
    round(2)

  p <-  pcoa$points %>% as_tibble %>% 
    cbind("City" = meta_sample$City) %>%
    ggplot(aes(x=V1,y=V2, color=City)) +
    geom_point(size=2) +
    theme_minimal() +
    xlab(paste("PCoA1 (~",varExplained_aitc[1],"%)", sep="")) +
    ylab(paste("PCoA2 (~",varExplained_aitc[2],"%)", sep="")) +
    theme(legend.position="none") +
    theme(title = element_text(size = 16))
}
```


```{r}
p.euc.pseo <- plot.PCOA.pseo(pcoa.euc, meta_sample, genus_rel_abund)
p.JSD.pseo <- plot.PCOA.pseo(pcoa.JSD, meta_sample, genus_rel_abund)
p.CAN.pseo <- plot.PCOA.pseo(pcoa.CAN, meta_sample, genus_rel_abund)
p.HEL.pseo <- plot.PCOA.pseo(pcoa.HEL, meta_sample, genus_rel_abund)
p.AIT.pseo <- plot.PCOA.pseo(pcoa.aitc, meta_sample, genus_rel_abund)
p.BRA.pseo <- plot.PCOA.pseo(pcoa.bray, meta_sample, genus_rel_abund)
```

```{r}
p.euc.city <- plot.PCOA.city(pcoa.euc, meta_sample)
p.JSD.city <- plot.PCOA.city(pcoa.JSD, meta_sample)
p.CAN.city <- plot.PCOA.city(pcoa.CAN, meta_sample)
p.HEL.city <- plot.PCOA.city(pcoa.HEL, meta_sample)
p.AIT.city <- plot.PCOA.city(pcoa.aitc, meta_sample)
p.BRA.city <- plot.PCOA.city(pcoa.bray, meta_sample)
```

```{r}
spacer_title <- ggplot() + 
  theme_void() +
  ggtitle("E-WADES Pseudomonadaceae") +
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"))
```

```{r, fig.width=24, fig.height=4.5}
p.pseo <- ggpubr::ggarrange(
  p.euc.pseo + ggtitle("Euclidian"),
  p.JSD.pseo + ggtitle("Jensen-Shannon"), 
  p.CAN.pseo + ggtitle("Canberra"), 
  p.HEL.pseo + ggtitle("Hellinger"),
  p.BRA.pseo + ggtitle("Bray-Curtis"),
  p.AIT.pseo + ggtitle("Aitchison"), 
  ncol = 6, legend = "none"
)
p.pseo <- ggpubr::ggarrange(spacer_title, p.pseo, nrow = 2, heights = c(.1, .9))
p.pseo
```

```{r}
spacer_title <- ggplot() + 
  theme_void() +
  ggtitle("E-WADES City") +
  theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"))
```

```{r, fig.width=24, fig.height=4.5}
p.city <- ggpubr::ggarrange(
  p.euc.city + ggtitle("Euclidian"), 
  p.JSD.city + ggtitle("Jensen-Shannon"), 
  p.CAN.city + ggtitle("Canberra"), 
  p.HEL.city + ggtitle("Hellinger"),
  p.BRA.city + ggtitle("Bray-Curtis"),
  p.AIT.city + ggtitle("Aitchison"), 
  ncol = 6, common.legend = T, legend = "none"
)
p.city <- ggpubr::ggarrange(spacer_title, p.city, nrow = 2, heights = c(.1, .9))
p.city
```

```{r, fig.width=24, fig.height=9}
pall <- ggpubr::ggarrange(p.pseo, p.city, nrow = 2)
pall
```

```{r}
png("../Supplementary/EWADES_pcoa_more_metrics.png", width = 2*7200, height = 2*2700, res = 2*300)
pall
dev.off()
```

