---
title: "R Notebook"
output: html_notebook
---

```{r, message=FALSE}
library(tidyverse)
library(grid)
library(png)
```

## More Metrics

```{r}
HMP2_metrics <- rasterGrob(readPNG("HMP2_pcoa_more_metrics.png"), interpolate = TRUE)
EWADES_metrics <- rasterGrob(readPNG("EWADES_pcoa_more_metrics.png"), interpolate = TRUE)
spacer <- ggplot() + theme_void()
```

```{r, fig.width = 24, fig.height=17.6}
pall <- ggpubr::ggarrange(
  HMP2_metrics,
  spacer,
  EWADES_metrics,
  nrow = 3,
  heights = c(1, 0.1, 1)
  #labels = c("G-HMP2", "", "E-WADES"), font.label = list(size = 18), label.y = 1.01
)
pall
```

```{r}
png(filename = "Sup1_more_metrics.png", width = 2*7200, height = 2*17.6*300, res = 2*300)
pall
dev.off()
```

## UMAP

```{r}
HMP2_umap <- rasterGrob(readPNG("HMP2_umap_metrics.png"), interpolate = TRUE)
EWADES_umap <- rasterGrob(readPNG("EWADES_umap_metrics.png"), interpolate = TRUE)
spacer <- ggplot() + theme_void()
```

```{r, fig.width = 10, fig.height=12.6}
pall <- ggpubr::ggarrange(
  HMP2_umap,
  spacer,
  EWADES_umap,
  nrow = 3,
  heights = c(1, 0.05, 1)
)
pall
```

```{r}
png(filename = "Sup2_umap.png", width = 3000, height = 12.6*300, res = 300)
pall
dev.off()
```




