---
title: "R Notebook"
output: html_notebook
---

```{r, message=FALSE}
library(tidyverse)
```

```{r, message=FALSE}
otu_abund <- read_csv("../../data/HMP2/abundance_HMP2.csv") %>%
  column_to_rownames("...1")
meta_sample <- read_csv("../../data/HMP2/meta_samples_HMP2.csv") %>%
  column_to_rownames("...1") %>% select(SubjectID) %>%
  rownames_to_column("sample")
otu_taxon <- read_csv("../../data/HMP2/taxonomy_HMP2.csv") %>%
  column_to_rownames("...1")
```

```{r}
all(rownames(otu_abund)==meta_sample$sample) &
all(colnames(otu_abund)==rownames(otu_taxon))
```

## Aggregate to Genus Rank

```{r}
genus_abund <- otu_abund %>% rownames_to_column("sample") %>%
  pivot_longer(-sample, names_to="otu", values_to="count") %>%
  left_join(otu_taxon%>%select(genus:otu), by="otu") %>%
  reframe(count=sum(count), .by=c("sample","genus")) %>%
  pivot_wider(names_from=genus, values_from=count) %>%
  column_to_rownames("sample")

genus_rel_abund <- data.frame(genus_abund/rowSums(genus_abund))
```

```{r}
subset_genera <- colSums(genus_abund) %>% sort %>% tail(10) %>% names
```

```{r}
set.seed(42)
colorGenera <- randomcoloR::distinctColorPalette(length(subset_genera)) %>%
  stats::setNames(subset_genera)
colorGenera["Bacteroides"] <- "#FF0000"
colorGenera["Prevotella"] <- "#00FF00"
colorGenera <- c(colorGenera, "Other"="#A6A6A6")
```

```{r}
p.composition <- genus_rel_abund %>%
  rownames_to_column("sample") %>%
  arrange(desc(Bacteroides - Prevotella)) %>%
  mutate(sample=as_factor(sample)) %>%
  pivot_longer(-sample, names_to="genus", values_to="relative") %>%
  mutate(genus = if_else(genus %in% subset_genera, genus, "Other")) %>%
  reframe(relative=sum(relative), .by=c("sample","genus")) %>%
  ggplot(aes(x=sample,y=relative,fill=genus)) +
    geom_bar(stat="identity") +
    scale_fill_manual(breaks=names(colorGenera),
                      values=colorGenera) +
    theme_minimal() +
    theme(legend.position="bottom",
          axis.text.x=element_blank(),
          axis.ticks.x=element_blank()) +
  ylab("Genera Composition") +
  guides(fill=guide_legend(ncol=6))
p.composition
```


## Enterotype Reasearch

```{r}
dist_JSD_genus <- genus_rel_abund %>%
  philentropy::distance("jensen-shannon") %>%
  as.dist
```

```{r}
df_index_G1=vector(mode="numeric", length=20)

for (k in 2:20) { 
    
    df_index_G1[k] <-dist_JSD_genus %>%
      cluster::pam(k=k, diss=TRUE) %>%
      .$clustering %>% as.vector() %>%
      clusterSim::index.G1(x=genus_rel_abund,
                           cl=.,
                           d=dist_JSD_genus,
                           centrotypes="medoids")
}

df_index_G1 <- data.frame("nCluster"=1:20, "index_G1"=df_index_G1)
```

```{r}
p.G1 <- df_index_G1 %>%
  ggplot(aes(x=nCluster, y=index_G1)) +
  #geom_col(color="darkblue", fill="lightblue") +
  geom_segment(aes(x=nCluster, xend=nCluster, y=0, yend=index_G1), color="#7D7D7D") + 
  geom_point(color="#FF7F0E", size=2.5) +
  theme_bw() +
  xlab("Number of Clusters") +
  ylab("Calinski-Harabasz\nIndex") +
  theme(axis.title=element_text(size=12)) +
  theme(plot.margin=margin(b=10))

rm(k)
p.G1
```

```{r}
meta_sample <- dist_JSD_genus %>%
  cluster::pam(k=3, diss=TRUE) %>%
  .$clustering %>% as.vector() %>%
  cbind(meta_sample, "cluster"=.) %>%
  mutate(enterotype=case_when(
    cluster==1 ~ "Bacteroides",
    cluster==2 ~ "Heterogeneous",
    cluster==3 ~ "Prevotella",
    .default="ERROR"
  ))
```


```{r}
p.box.ent <- genus_rel_abund%>%
  select(all_of(subset_genera)) %>%
  rownames_to_column("sample") %>%
  pivot_longer(-sample, names_to="genus",values_to="relative") %>%
  left_join(meta_sample, by="sample") %>%
  mutate(genus=str_replace_all(genus,"_","\n")) %>%
  ggplot(aes(x=genus, y=relative, fill=enterotype)) +
  #facet_wrap(~genus, scales="free") +
  geom_boxplot() +
  theme_bw() +
  theme(axis.text=element_text(size=9),
        axis.text.x=element_text(angle=45, hjust=1)) +
  labs(fill="Enterotype") +
  theme(legend.position="bottom") +
  ylab("Relative Abundance") +
  scale_fill_manual(breaks=c("Bacteroides","Heterogeneous", "Prevotella"),
                    values=c( "#FF0000","#3399FF","#00FF00")) +
  theme(legend.position="right",
        axis.title.x=element_blank())
p.box.ent
```

## Dimensionality Reduction

```{r}
# choose only sample with at least 25 sample to improve the clarity 
# in the results
subject_preserved <- meta_sample$SubjectID %>% table %>%
  subset(.>=25) %>% names
```

```{r}
# Useful function

prevalence <- function(X){colSums(X>0)/nrow(X)}

zero_replacement <- function(X){
  dl <- apply(X,1,\(x) .65*min(x[x>0]))
  dl <- replicate(ncol(X),dl)
  X <- X + dl*(X==0)
  return(X)
}

clr <- function(X){
  ref <- apply(X, 1, function(x) mean(log(x)) )
  return(as.matrix(log(X) - ref))
}
```

```{r}
# Filter relative abundance matrix to preserve the subjects with at least 25 samples
# and to remove the rarer genera
genus_rel_abund_filt <- genus_rel_abund[meta_sample$SubjectID%in%subject_preserved,]
genus_rel_abund_filt <- genus_rel_abund_filt[,prevalence(genus_rel_abund_filt)>=.10]
meta_sample_filt <- meta_sample[meta_sample$SubjectID%in%subject_preserved,]
```

```{r}
# Calculate the distance matrix with bray-curtis and aitchison
dist.bray <- vegan::vegdist(genus_rel_abund_filt,"bray") %>% as.dist
dist.aitc <- genus_rel_abund_filt %>% zero_replacement %>% clr %>% dist %>% as.dist
```

## PCOA

```{r}
pcoa.bray <- stats::cmdscale(dist.bray, eig=T, add=T)
pcoa.aitc <- stats::cmdscale(dist.aitc, eig=T, add=T)
```

## Plot with Aitchison Distance

```{r}
centroids.pcoa.aitc <- pcoa.aitc$points %>% as_tibble %>%
  cbind("Subjects"=meta_sample_filt$SubjectID) %>%
  reframe(V1=mean(V1), 
          V2=mean(V2),
          .by=Subjects)

varExplained_aitc <- 100 * (pcoa.aitc$eig / sum(pcoa.aitc$eig)) %>%
  round(2)

p.pcoa.aitc <-  pcoa.aitc$points %>% as_tibble %>% 
  cbind("Subjects"=meta_sample_filt$SubjectID) %>%
  ggplot(aes(x=V1,y=V2, color=Subjects)) +
  geom_point(size=3) +
  stat_ellipse() +
  geom_point(data=centroids.pcoa.aitc, shape=21, size=5, color="black",
             aes(fill=Subjects)) +
  theme_minimal() +
  xlab(paste("PCoA1 (~",varExplained_aitc[1],"%)", sep="")) +
  ylab(paste("PCoA1 (~",varExplained_aitc[2],"%)", sep="")) +
  theme(legend.position="bottom")

p.pcoa.aitc
```

```{r}
varExplained_bray <- 100 * (pcoa.bray$eig / sum(pcoa.bray$eig)) %>%
  round(2)

p.pcoa.bray <- pcoa.bray$points %>% as_tibble %>% 
  cbind("Bacteroides"=genus_rel_abund_filt[,"Bacteroides"]) %>%
  cbind("Prevotella"=genus_rel_abund_filt[,"Prevotella"]) %>%
  as_tibble() %>% mutate(sample=meta_sample_filt$sample) %>%
  left_join(meta_sample_filt, by="sample") %>%
  mutate(enterotype=as.factor(enterotype)) %>%
  mutate(color_metric=Bacteroides-Prevotella) %>%
  mutate(color_metric_2=rgb(Bacteroides,Prevotella,0)) %>%
  ggplot(aes(x=V1, y=V2)) +
    geom_point(aes(color=color_metric_2, shape=enterotype), size=3) +
    scale_color_identity() +
    theme_minimal() +
    theme(legend.position="bottom",
          legend.justification=1) +
    xlab(paste("PCoA1 (~",varExplained_bray[1],"%)", sep="")) +
    ylab(paste("PCoA1 (~",varExplained_bray[2],"%)", sep="")) +
    guides(shape=guide_legend(label.position="top", title.position="top",
                              title.hjust=.5)) +
    ggnewscale::new_scale_color() +
      geom_point(aes(x = V1, y = V2, color = Prevotella), alpha = 0) +
      scale_color_gradient(name="Prevotella", low="black", high="green", 
                           limits=c(0,.75)) +
      theme(legend.position="bottom") +
    ggnewscale::new_scale_color() +
      geom_point(aes(x = V1, y = V2, color = Bacteroides), alpha = 0) +
      scale_color_gradient(name="Bacteroides", low="black", high="red", 
                           limits=c(0,.75)) +
      theme(legend.position = "bottom",
            legend.justification=0)
```


## Merge the figures

```{r}
p1 <- ggpubr::ggarrange(p.G1 + theme(plot.margin=margin(b=50)), p.box.ent, ncol=2, labels=c("A","B"), 
                        common.legend=T, legend="top", widths=c(.2,.8))

p2 <- ggpubr::ggarrange(p.pcoa.bray, p.pcoa.aitc, ncol=2, labels=c("C","D"))

pall <- ggpubr::ggarrange(p1, p2, 
                          p.composition, 
                          ncol=1, labels=c("","","E"),
                          heights=c(.25, 0.45,0.25))
```

```{r}
# png(filename="HMP2_pcoa_metrics.png", width=4000, height=4500, res=300)
# pall
# dev.off()
```

```{r}
pdf(file="HMP2_pcoa_metrics.pdf", width=13, height=13)
pall
dev.off()
```

## The same but with metaMDS

## metaMDS

```{r}
nmds.bray <- vegan::metaMDS(dist.bray)
nmds.aitc <- vegan::metaMDS(dist.aitc)
```

## Plot with Aitchison Distance

```{r}
centroids.nmds.aitc <- vegan::scores(nmds.aitc) %>% as_tibble %>%
  cbind("Subjects"=meta_sample_filt$SubjectID) %>%
  reframe(NMDS1=mean(NMDS1), 
          NMDS2=mean(NMDS2),
          .by=Subjects)

p.nmds.aitc <-  vegan::scores(nmds.aitc) %>% as_tibble %>% 
  cbind("Subjects"=meta_sample_filt$SubjectID) %>%
  ggplot(aes(x=NMDS1,y=NMDS2, color=Subjects)) +
  geom_point(size=3) +
  stat_ellipse() +
  geom_point(data=centroids.nmds.aitc, shape=21, size=5, color="black",
             aes(fill=Subjects)) +
  theme_minimal() +
  #xlab(paste("nmds1 (~",varExplained_aitc[1],"%)", sep="")) +
  #ylab(paste("nmds1 (~",varExplained_aitc[2],"%)", sep="")) +
  theme(legend.position="bottom")

p.nmds.aitc
```

```{r}
p.nmds.bray <- vegan::scores(nmds.bray) %>% as_tibble %>% 
  cbind("Bacteroides"=genus_rel_abund_filt[,"Bacteroides"]) %>%
  cbind("Prevotella"=genus_rel_abund_filt[,"Prevotella"]) %>%
  as_tibble() %>% mutate(sample=meta_sample_filt$sample) %>%
  left_join(meta_sample_filt, by="sample") %>%
  mutate(enterotype=as.factor(enterotype)) %>%
  mutate(color_metric=Bacteroides-Prevotella) %>%
  mutate(color_metric_2=rgb(Bacteroides,Prevotella,0)) %>%
  ggplot(aes(x=NMDS1, y=NMDS2)) +
    geom_point(aes(color=color_metric_2, shape=enterotype), size=3) +
    scale_color_identity() +
    theme_minimal() +
    theme(legend.position="bottom",
          legend.justification=1) +
    #xlab(paste("PCoA1 (~",varExplained_bray[1],"%)", sep="")) +
    #ylab(paste("PCoA1 (~",varExplained_bray[2],"%)", sep="")) +
    guides(shape=guide_legend(label.position="top", title.position="top",
                              title.hjust=.5)) +
    ggnewscale::new_scale_color() +
      geom_point(aes(x = NMDS1, y = NMDS2, color = Prevotella), alpha = 0) +
      scale_color_gradient(name="Prevotella", low="black", high="green", 
                           limits=c(0,.75)) +
      theme(legend.position="bottom") +
    ggnewscale::new_scale_color() +
      geom_point(aes(x = NMDS1, y = NMDS2, color = Bacteroides), alpha = 0) +
      scale_color_gradient(name="Bacteroides", low="black", high="red", 
                           limits=c(0,.75)) +
      theme(legend.position = "bottom",
            legend.justification=0)
```

## Merge the figures

```{r}
p1 <- ggpubr::ggarrange(p.G1 + theme(plot.margin=margin(b=50)), p.box.ent, ncol=2, labels=c("A","B"), 
                        common.legend=T, legend="top", widths=c(.2,.8))

p2 <- ggpubr::ggarrange(p.nmds.bray, p.nmds.aitc, ncol=2, labels=c("C","D"))

pall <- ggpubr::ggarrange(p1, p2, p.composition, ncol=1, labels=c("","","E"),
                          heights=c(.25, 0.45,0.25))
```

```{r}
png(filename="HMP2_nmds_metrics.png", width=4000, height=4500, res=300)
pall
dev.off()
```





